name: Mirror to Codeberg

on: [push]
jobs:
  sync-git:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://codeberg.org/LucasGGamerM/moshidon.git'
        GIT_USERNAME: LucasGGamerM
        GIT_PASSWORD: ${{ secrets.CODEBERG_GIT_PASSWORD }}
